### ISSUE TITLE
unhandled promise rejection 

### ISSUE THREAD

**Issue by Geczy** [chiefsmurph/robinhood-playground#6]
All I did was npm start

```
looking at 11000 results
canceling all orders...
orders []
(node:16980) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '
map' of undefined
    at module.exports (C:\Users\Matt\Documents\GitHub\robinhood-playground2\app-
actions\log-portfolio-value.js:18:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:16980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:16980) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
Done in 89.36s.

```

**Comment by Geczy** [comment]
```
    let {equity_historicals: hist} = await Robinhood.url('https://api.robinhood.com/portfolios/historicals/5SA80442/?span=year&interval=day');

```

Guessing because the URL is your own profile ID

**Comment by Geczy** [comment]
Changed it to my ID, but now this error:

```
orders []
[] 'strategies enabled '
unable to init C:\Users\Matt\Documents\GitHub\robinhood-playground2\modules/patt
ern-predict { Error: Cannot find module './stock-fns/runOutlookAndTestsOnStockCS
V'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Matt\Documents\GitHub\robinhood-playground2\
modules\pattern-predict\index.js:7:38)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
unable to init C:\Users\Matt\Documents\GitHub\robinhood-playground2\modules/scra
pes TypeError: Cannot read property 'topBuy' of undefined
    at Object.<anonymous> (C:\Users\Matt\Documents\GitHub\robinhood-playground2\
modules\scrapes\stockinvest.js:7:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Matt\Documents\GitHub\robinhood-playground2\
modules\scrapes\index.js:10:21)
    at Module._compile (module.js:652:30)
06:31:00 31 6 * * * execute week-swings strategy  -

```

**Comment by Geczy** [comment]
```
getting trend since open for all stocks - 6:31am + 242* minutes
multiple
(node:19352) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or di
rectory, open 'C:\Users\Matt\Documents\GitHub\robinhood-playground2\stock-data\2
018-4-4 10:32:05 (+242*).json'
(node:19352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:19352) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

```
